CREATE SEQUENCE CLIENT_SEQUENCE START WITH 20 INCREMENT BY 1;
CREATE SEQUENCE ASSURANCE_SEQUENCE START WITH 20 INCREMENT BY 1;
 

CREATE TABLE CLIENT(
	idClient INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
	primary key (idClient)
);

create table ECHEANCES(
idEcheance INTEGER,
prix integer,
dateEmission date,
datePaiement date,
dateEmissionFacture date,
primary key (idEcheance)
);


CREATE TABLE COMPTE_BANCAIRE(
	iban varchar(32),
	proprietaire VARCHAR (50),
	swift_code varchar(8),
	principal boolean,
	idClient integer,
	PRIMARY KEY (iban),
	FOREIGN KEY (idClient) REFERENCES CLIENT(idClient)
);

create TABLE ASSURANCE(
    idAssurance INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
    dateSouscription date,
	dateAnniversaire date,
	datePrelevement date,
	idEcheance integer,
    PRIMARY KEY (idAssurance),
	foreign key (idEcheance) REFERENCES ECHEANCES(idEcheance)
  );

  create TABLE CLIENT_ASSURANCE(
    idClient INTEGER ,
    idAssurance INTEGER ,
    PRIMARY KEY (idClient, idAssurance),
    FOREIGN KEY (idClient) REFERENCES CLIENT(idClient),
    FOREIGN KEY (idAssurance) REFERENCES ASSURANCE(idAssurance)
  );
  
  create TABLE CONTACT(
	idClient INTEGER,
	type VARCHAR(20),
	valeur VARCHAR(20)
  );
  
	
create TABLE PERSONNE_PHYSIQUE(
	idClient INTEGER,
	nom VARCHAR(50),
	prenom VARCHAR(50),
	dateNaissance date,
	primary key (idClient),
	foreign key (idClient) REFERENCES CLIENT(idClient)
);

create table PERSONNE_MORALE(
	idClient INTEGER,
	nom VARCHAR(50),
	siren varchar(10),
	primary key (idClient),
	foreign key (idClient) REFERENCES CLIENT(idClient)
);


create table ASSURANCE_AUTO(
	idAssurance INTEGER,
	immatriculation VARCHAR(15),
	bonus_malus decimal(4,2),
	primary key (idAssurance),
	foreign key (idAssurance) REFERENCES ASSURANCE(idAssurance)
);

create table ASSURANCE_HABITATION(
idAssurance INTEGER,
adresse VARCHAR(255),
valeurConverture INTEGER,
primary key (idAssurance),
	foreign key (idAssurance) REFERENCES ASSURANCE(idAssurance)
);




create table sinistre(
idSinistre integer GENERATED BY DEFAULT AS IDENTITY (start with 1),
idAssurance integer,
idClient integer,
date date,
titre VARCHAR(20),
description varchar(255),
primary key (idSinistre),
	foreign key (idAssurance) REFERENCES ASSURANCE(idAssurance),
foreign key (idClient) REFERENCES CLIENT(idClient)
);