CREATE SEQUENCE CLIENT_SEQUENCE START WITH 20 INCREMENT BY 1;
CREATE SEQUENCE ASSURANCE_SEQUENCE START WITH 20 INCREMENT BY 1;

CREATE TABLE COMPTE_BANCAIRE(
	iban varchar(32),
	proprietaire VARCHAR (50),
	swift_code varchar(8),
	PRIMARY KEY (iban)
);
 

CREATE TABLE CLIENT(
	idClient INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
	primary key (idClient)
);



CREATE TABLE COMPTE_CLIENT(
  idClient INTEGER ,
  iban varchar(20),
  principal tinyint(2),
  PRIMARY KEY (idClient, iban),
	FOREIGN KEY (idClient) REFERENCES CLIENT(idClient),
  FOREIGN KEY (iban) REFERENCES COMPTE_BANCAIRE(iban)
);


create TABLE ASSURANCE(
    idAssurance INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
    dateSouscription date,
	dateAnniversaire date,
	datePrelevement date,
    PRIMARY KEY (idAssurance)
  );

  create TABLE CLIENT_ASSURANCE(
    idClient INTEGER ,
    idAssurance INTEGER ,
    PRIMARY KEY (idClient, idAssurance),
    FOREIGN KEY (idClient) REFERENCES CLIENT(idClient),
    FOREIGN KEY (idAssurance) REFERENCES ASSURANCE(idAssurance)
  );
  
  create TABLE CONTACT(
	idClient INTEGER,
	type VARCHAR(20),
	valeur VARCHAR(20)
  );
  
	
create TABLE PERSONNE_PHYSIQUE(
	idClient INTEGER,
	nom VARCHAR(50),
	prenom VARCHAR(50),
	dateNaissance date,
	primary key (idClient),
	foreign key (idClient) REFERENCES CLIENT(idClient)
);

create table PERSONNE_MORALE(
	idClient INTEGER,
	nom VARCHAR(50),
	primary key (idClient),
	foreign key (idClient) REFERENCES CLIENT(idClient)
);


create table ASSURANCE_AUTO(
	idAssurance INTEGER,
	immatriculation VARCHAR(15),
	bonus_malus decimal(4,2),
	primary key (idAssurance),
	foreign key (idAssurance) REFERENCES ASSURANCE(idAssurance)
);

create table ASSURANCE_HABITATION(
idAssurance INTEGER,
adresse VARCHAR(255),
valeurConverture INTEGER,
primary key (idAssurance),
	foreign key (idAssurance) REFERENCES ASSURANCE(idAssurance)
);

create table ECHEANCES(
idAssurance INTEGER,
prix integer,
dateEmission date,
datePaiement date,
dateEmissionFacture date,
primary key (idAssurance),
	foreign key (idAssurance) REFERENCES ASSURANCE(idAssurance)
);